# Generated by Django 6.0.3 on 2026-03-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=100)),
                ("product_gid", models.CharField(max_length=255)),
                ("handle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "updated_at_shopify",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "products",
                "unique_together": {("store_name", "product_gid")},
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=100)),
                ("variant_gid", models.CharField(max_length=255)),
                ("product_gid", models.CharField(max_length=255)),
                (
                    "inventory_item_gid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "updated_at_shopify",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "variants",
                "unique_together": {("store_name", "variant_gid")},
            },
        ),
    ]
