# Generated by Django 6.0.3 on 2026-03-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0002_store_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                ("updated", models.IntegerField(default=0)),
                ("created", models.IntegerField(default=0)),
                ("skipped", models.IntegerField(default=0)),
                ("deleted", models.IntegerField(default=0)),
                ("errors", models.IntegerField(default=0)),
                ("conflicts", models.IntegerField(default=0)),
                ("status", models.CharField(default="success", max_length=20)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "sync_logs",
                "ordering": ["-started_at"],
            },
        ),
    ]
