# Generated by Django 6.0.3 on 2026-03-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syncing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="synclog",
            name="log_type",
            field=models.CharField(
                choices=[("sync", "Sync"), ("fetch", "Fetch")],
                default="sync",
                max_length=10,
            ),
        ),
    ]
