# Generated by Django 6.0.3 on 2026-03-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "store_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("access_token", models.CharField(blank=True, max_length=255)),
                ("scopes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stores",
            },
        ),
    ]
