# Generated by Django 6.0.3 on 2026-03-28 14:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_store_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="store",
            unique_together={("store_name", "user")},
        ),
    ]
